### ISSUE TITLE
Don't prepend resource class name to flavor name automatically

### ISSUE THREAD

**Issue by jistr** [tuskar/tuskar#89]
We prepend resource class name to the flavor name in the API. This means that client sends request it wants a new flavor named "small" and gets back a flavor named "m1.small". I find this somewhat confusing. (It's not obvious how should update of the name be done. Should client send "m1.small" or strip it and send just "small" again?)

My opinion is we should have API just check that the right prefix is sent from the client.

**Comment by marios** [comment]
Hey @jistr - so i spent  a while thinking about this and it sounds like a legitimate issue/concern. However I then did a sanity check and tried it - not sure if this changed from when the issue was reported but I am not seeing the behaviour described above. This is what I did:
1. rm tuskar.sqlite. restart tuskar (db migrate etc).
2. python sample_data.py
3. Resource Class with id 2 is created and has no flavors - so create one:
   
   curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d '
   {
          "max_vms": 10,
          "name": "tiny",
          "capacities":
          [
              {
                  "value": "1",
                  "name": "cpu",
                  "unit": "count"
              },
              {
                  "value": "512",
                  "name": "memory",
                  "unit": "MiB"
              },
              {
                  "value": "512",
                  "name": "storage",
                  "unit": "GiB"
              }
          ]
    }' http://0.0.0.0:6385/v1/resource_classes/2/flavors

The response I got was for a flavor with name 'tiny'. I retrieved the flavors collection for resource class 2 to confirm and also checked the database. I looked at the create code and I'm not putting the resource class name there. We DO set the name of the flavor created IN NOVA to be rc_name.flavor_name - but this happens when you provision (i.e. generate the HEAT template). Not sure if we need to pursue this further at this point?

thanks, marios

**Comment by jistr** [comment]
So the problem is different than I originally thought. We consistently use only the flavor name when talking to the client, so that's good. We just name the flavor with a resource class name prefix when talking to Nova. It might be better to stay consistent across the whole stack (use the prefixed names everywhere), but it's an unimportant issue. We would get back to this if we thought it would create any trouble in the future. Closing the issue.
